name: todos_app
description: "Aplicativo de lista de tarefas."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  logging: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  hard_analyser: ^1.9.0
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/
    - assets/splash/
    - lib/ui/core/l10n/
